export const genders = [
  {
    id: 1,
    value: 'Male',
    slug: 'male',
  },
  {
    id: 2,
    value: 'Female',
    slug: 'female',
  },
  {
    id: 3,
    value: 'Other',
    slug: 'other',
  },
];

export const nationalities = [
  {
    id: 4,
    value: 'Nepalese',
    slug: 'nepalese',
  },
  {
    id: 5,
    value: 'Indian',
    slug: 'indian',
  },
  {
    id: 6,
    value: 'Foreigners',
    slug: 'foreigners',
  },
];

export const provinces = [
  {
    id: 2,
    name: 'Province 1',
    slug: 'province-1',
  },
  {
    id: 3,
    name: 'Madhesh Province',
    slug: 'madhesh-province',
  },
  {
    id: 4,
    name: 'Bagmati Province',
    slug: 'bagmati-province',
  },
  {
    id: 5,
    name: 'Gandaki Province',
    slug: 'gandaki-province',
  },
  {
    id: 6,
    name: 'Lumbini Province',
    slug: 'lumbini-province',
  },
  {
    id: 7,
    name: 'Karnali Province',
    slug: 'karnali-province',
  },
  {
    id: 8,
    name: 'Sudurpashchim Province',
    slug: 'sudurpashchim-province',
  },
];

export const districts = [
  { id: 163, slug: 'bhojpur' },
  { id: 164, slug: 'dhankuta' },
  { id: 165, slug: 'ilam' },
  { id: 166, slug: 'jhapa' },
  { id: 167, slug: 'khotang' },
  { id: 168, slug: 'morang' },
  { id: 169, slug: 'okhaldhunga' },
  { id: 170, slug: 'panchthar' },
  { id: 171, slug: 'sankhuwasabha' },
  { id: 172, slug: 'solukhumbu' },
  { id: 173, slug: 'sunsari' },
  { id: 174, slug: 'taplejung' },
  { id: 175, slug: 'terhathum' },
  { id: 176, slug: 'udayapur' },
  { id: 177, slug: 'saptari' },
  { id: 178, slug: 'siraha' },
  { id: 179, slug: 'dhanusha' },
  { id: 180, slug: 'mahottari' },
  { id: 181, slug: 'sarlahi' },
  { id: 182, slug: 'bara' },
  { id: 183, slug: 'parsa' },
  { id: 184, slug: 'rautahat' },
  { id: 185, slug: 'sindhuli' },
  { id: 186, slug: 'ramechhap' },
  { id: 187, slug: 'dolakha' },
  { id: 188, slug: 'bhaktapur' },
  { id: 189, slug: 'dhading' },
  { id: 190, slug: 'kathmandu' },
  { id: 191, slug: 'kavrepalanchowk' },
  { id: 192, slug: 'lalitpur' },
  { id: 193, slug: 'nuwakot' },
  { id: 194, slug: 'rasuwa' },
  { id: 195, slug: 'sindhupalchok' },
  { id: 196, slug: 'chitwan' },
  { id: 197, slug: 'makawanpur' },
  { id: 198, slug: 'baglung' },
  { id: 199, slug: 'gorkha' },
  { id: 200, slug: 'kaski' },
  { id: 201, slug: 'lamjung' },
  { id: 202, slug: 'manang' },
  { id: 203, slug: 'mustang' },
  { id: 204, slug: 'myagdi' },
  { id: 205, slug: 'nawalpur' },
  { id: 206, slug: 'parbat' },
  { id: 207, slug: 'syangja' },
  { id: 208, slug: 'tanahun' },
  { id: 209, slug: 'kapilvastu' },
  { id: 210, slug: 'nawalparasi' },
  { id: 211, slug: 'rupandehi' },
  { id: 212, slug: 'arghakhanchi' },
  { id: 213, slug: 'gulmi' },
  { id: 214, slug: 'palpa' },
  { id: 215, slug: 'dang' },
  { id: 216, slug: 'pyuthan' },
  { id: 217, slug: 'rolpa' },
  { id: 218, slug: 'eastern-rukum' },
  { id: 219, slug: 'banke' },
  { id: 220, slug: 'bardiya' },
  { id: 221, slug: 'western-rukum' },
  { id: 222, slug: 'salyan' },
  { id: 223, slug: 'dolpa' },
  { id: 224, slug: 'humla' },
  { id: 225, slug: 'jumla' },
  { id: 226, slug: 'kalikot' },
  { id: 227, slug: 'mugu' },
  { id: 228, slug: 'surkhet' },
  { id: 229, slug: 'dailekh' },
  { id: 230, slug: 'jajarkot' },
  { id: 231, slug: 'kailali' },
  { id: 232, slug: 'achham' },
  { id: 233, slug: 'doti' },
  { id: 234, slug: 'bajhang' },
  { id: 235, slug: 'bajura' },
  { id: 236, slug: 'kanchanpur' },
  { id: 237, slug: 'dadeldhura' },
  { id: 238, slug: 'baitadi' },
  { id: 239, slug: 'darchula' },
];
