/* eslint-disable */
"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert(
      "modules",
      [
        //dashboard
        {
          id: 1,
          name: "Dashboard Notifications", 
          slug: "dashboard-notifications",
          is_default: true,
          screen_id: 1,
          status:"active",
          description:"",
          created_at: new Date(),
          updated_at: new Date(),
        }, 
        {
          id: 2,
          name: "Dashboard Template",
          slug: "dashboard-template",
          is_default: true,
          screen_id: 1,
          status:"active",
          description:"",
          created_at: new Date(),
          updated_at: new Date(),
        }, 
        //customer
        {
          id: 3,
          name: "Customer Header",
          slug: "customer-header",
          is_default: true,
          screen_id: 2,
          status:"active",
          description:"",
          created_at: new Date(),
          updated_at: new Date(),
        }, 
        {
          id: 4,
          name: "Customer Table",
          slug: "customer-table",
          is_default: true,
          screen_id: 2,
          status:"active",
          description:"",
          created_at: new Date(),
          updated_at: new Date(),
        }, 
        // email group
        {
          id: 5,
          name: "Email Group Header",
          slug: "email-group-header",
          is_default: true,
          screen_id: 3,
          status:"active",
          description:"",
          created_at: new Date(),
          updated_at: new Date(),
        }, 
        {
          id: 6,
          name: "Email Group Table",
          slug: "email-group-table",
          is_default: true,
          screen_id: 3,
          status:"active",
          description:"",
          created_at: new Date(),
          updated_at: new Date(),
        }, 
        // message group
        {
          id: 7,
          name: "Message Group Header",
          slug: "message-group-header",
          is_default: true,
          screen_id: 4,
          status:"active",
          description:"",
          created_at: new Date(),
          updated_at: new Date(),
        }, 
        {
          id: 8,
          name: "Message Group Table",
          slug: "message-group-table",
          is_default: true,
          screen_id: 4,
          status:"active",
          description:"",
          created_at: new Date(),
          updated_at: new Date(),
        }, 
        //template
        {
          id: 9,
          name: "Template Header",
          slug: "template-header",
          is_default: true,
          screen_id: 5,
          status:"active",
          description:"",
          created_at: new Date(),
          updated_at: new Date(),
        }, 
        {
          id: 10,
          name: "Template Table",
          slug: "template-table",
          is_default: true,
          screen_id: 5,
          status:"active",
          description:"",
          created_at: new Date(),
          updated_at: new Date(),
        }, 
        //campaign
        {
          id: 11,
          name: "Campaign Header",
          slug: "campaign-header",
          is_default: true,
          screen_id: 6,
          status:"active",
          description:"",
          created_at: new Date(),
          updated_at: new Date(),
        }, 
        {
          id: 12,
          name: "Campaign Table",
          slug: "campaign-table",
          is_default: true,
          screen_id: 6,
          status:"active",
          description:"",
          created_at: new Date(),
          updated_at: new Date(),
        }, 
        //Members
        {
          id: 13,
          name: "Members Header",
          slug: "members-header",
          is_default: true,
          screen_id: 9,
          status:"active",
          description:"",
          created_at: new Date(),
          updated_at: new Date(),
        }, 
        {
          id: 14,
          name: "Members Table",
          slug: "members-table",
          is_default: true,
          screen_id: 9,
          status:"active",
          description:"",
          created_at: new Date(),
          updated_at: new Date(),
        },
        // settings
        {
          id: 15,
          name: "Settings General",
          slug: "settings-general",
          is_default: true,
          screen_id: 11,
          status:"active",
          description:"",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 16,
          name: "Identity Verification",
          slug: "identity-verification",
          is_default: true,
          screen_id: 11,
          status:"active",
          description:"",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 17,
          name: "Settings Permissions",
          slug: "settings-permissions",
          is_default: true,
          screen_id: 11,
          status:"active",
          description:"",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 18,
          name: "Testing Preferences",
          slug: "testing-preferences",
          is_default: true,
          screen_id: 11,
          status:"active",
          description:"",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 19,
          name: "GDPR Features",
          slug: "gdpr-features",
          is_default: true,
          screen_id: 11,
          status:"active",
          description:"",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 20,
          name: "Google ReCAPTCHA",
          slug: "google-recaptcha",
          is_default: true,
          screen_id: 11,
          status:"active",
          description:"",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 21,
          name: "Settings Miscellaneous",
          slug: "settings-miscellaneous",
          is_default: true,
          screen_id: 11,
          status:"active",
          description:"",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 22,
          name: "Settings Notifications",
          slug: "settings-notifications",
          is_default: true,
          screen_id: 11,
          status:"active",
          description:"",
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete("modules", [], {});
  },
};
