name: Deploy to AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install npm 
        run: npm install --legacy-peer-deps # Install dependencies

      - name: NPM BUILD
        run: npm run build
        
      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Deploy to AWS
        run: |
          serverless deploy --verbose --config serverless-development.yml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}